spring:
  profiles:
    active: dev
  application:
    name: survey-analyst-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 邮件配置（敏感信息，不上传）
  mail:
    username: 3050604024@qq.com  # 发送邮件的邮箱
    password: rxhidqusgbsmdcgh  # 邮箱授权码

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      enabled: false  # 禁用Spring Boot的自动字符编码过滤器，使用自定义过滤器处理字符编码（排除导出接口）
